ALTER TABLE users ADD COLUMN terms_version TEXT NOT NULL DEFAULT '2026-07-06';
ALTER TABLE users ADD COLUMN privacy_version TEXT NOT NULL DEFAULT '2026-07-06';
ALTER TABLE users ADD COLUMN agreed_at INTEGER NOT NULL DEFAULT 0;
